dubbo:
  application:
    name: Infor-class
  registry:
    address: zookeeper://47.106.39.234:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql://47.106.39.234/db_class?serverTimezone=GMT%2B8
    username: root
    password: qwerQWER1234_
    driver-class-name: com.mysql.cj.jdbc.Driver